name: frontend

on:
  push:
    paths:
    - ".github/workflows/frontend.yml"
    - "html/*"
  pull_request:
    paths:
    - ".github/workflows/frontend.yml"
    - "html/*"

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Run yarn install, check and build
        run: |
          cd html
          yarn install
          yarn run check
          yarn run build
