/*
 * WARNING: do not edit!
 * Generated by util/mkbuildinf.pl
 *
 * Copyright 2014-2017 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#define PLATFORM "platform: linux-mips32"
#define DATE "built on: Tue Mar 22 01:57:45 2022 UTC"

/*
 * Generate compiler_flags as an array of individual characters. This is a
 * workaround for the situation where CFLAGS gets too long for a C90 string
 * literal
 */
static const char compiler_flags[] = {
    'c','o','m','p','i','l','e','r',':',' ','/','o','p','t','/','r',
    't','-','n','5','6','u','/','t','r','u','n','k','/','.','.','/',
    't','o','o','l','c','h','a','i','n','-','m','i','p','s','e','l',
    '/','t','o','o','l','c','h','a','i','n','-','3','.','4','.','x',
    '/','b','i','n','/','m','i','p','s','e','l','-','l','i','n','u',
    'x','-','u','c','l','i','b','c','-','g','c','c',' ','-','f','P',
    'I','C',' ','-','m','a','b','i','=','3','2',' ','-','m','i','p',
    's','2',' ','-','W','a',',','-','-','n','o','e','x','e','c','s',
    't','a','c','k',' ','-','m','i','p','s','3','2','r','2',' ','-',
    'm','a','r','c','h','=','m','i','p','s','3','2','r','2',' ','-',
    'm','t','u','n','e','=','1','0','0','4','k','c',' ','-','O','3',
    ' ','-','m','i','p','s','3','2','r','2',' ','-','m','a','r','c',
    'h','=','m','i','p','s','3','2','r','2',' ','-','m','t','u','n',
    'e','=','1','0','0','4','k','c',' ','-','f','o','m','i','t','-',
    'f','r','a','m','e','-','p','o','i','n','t','e','r',' ','-','p',
    'i','p','e',' ','-','D','E','M','B','E','D',' ','-','D','l','i',
    'n','u','x',' ','-','D','_','_','l','i','n','u','x','_','_',' ',
    '-','D','u','n','i','x',' ','-','W','a','l','l',' ','-','W','n',
    'o','-','t','r','i','g','r','a','p','h','s',' ','-','W','n','o',
    '-','s','t','r','i','c','t','-','a','l','i','a','s','i','n','g',
    ' ','-','W','n','o','-','f','o','r','m','a','t','-','s','e','c',
    'u','r','i','t','y',' ','-','f','n','o','-','t','r','e','e','-',
    's','l','s','r',' ','-','f','n','o','-','a','g','g','r','e','s',
    's','i','v','e','-','l','o','o','p','-','o','p','t','i','m','i',
    'z','a','t','i','o','n','s',' ','-','W','n','o','-','p','o','i',
    'n','t','e','r','-','s','i','g','n',' ','-','W','n','o','-','u',
    'n','u','s','e','d',' ','-','f','f','u','n','c','t','i','o','n',
    '-','s','e','c','t','i','o','n','s',' ','-','f','d','a','t','a',
    '-','s','e','c','t','i','o','n','s',' ','-','D','O','P','E','N',
    'S','S','L','_','U','S','E','_','I','P','V','6','=','1',' ','-',
    'D','O','P','E','N','S','S','L','_','P','R','E','F','E','R','_',
    'C','H','A','C','H','A','_','O','V','E','R','_','G','C','M',' ',
    '-','D','O','P','E','N','S','S','L','_','U','S','E','_','I','P',
    'V','6','=','1',' ','-','D','O','P','E','N','S','S','L','_','P',
    'R','E','F','E','R','_','C','H','A','C','H','A','_','O','V','E',
    'R','_','G','C','M',' ','-','D','O','P','E','N','S','S','L','_',
    'U','S','E','_','N','O','D','E','L','E','T','E',' ','-','D','O',
    'P','E','N','S','S','L','_','P','I','C',' ','-','D','O','P','E',
    'N','S','S','L','_','B','N','_','A','S','M','_','M','O','N','T',
    ' ','-','D','S','H','A','1','_','A','S','M',' ','-','D','S','H',
    'A','2','5','6','_','A','S','M',' ','-','D','A','E','S','_','A',
    'S','M',' ','-','D','N','D','E','B','U','G','\0'
};
